### PR TITLE
README changes

### PR DESCRIPTION
**Pull request by modded-soldier-9**
i have changed README.md to look much better and more appealing and user and friendly

### CODE REVIEW

**Review by tshamala-pathy — APPROVED** [review]
Hi Mohamed, thank you for reviewing the changes you've made to the readme file. I appreciate your effort, and I agree that it now looks good.👌

**Comment by modded-soldier-9** [comment]
iam glad i could help :)

**Comment by modded-soldier-9** [comment]
iam glad i could help :)

**Comment by tshamala-pathy** [comment]
Hi Mohamed, your feedback and contributions have been invaluable. Your attention to detail and dedication to improving our project are truly appreciated. I encourage you to continue sharing your ideas and suggestions. Together, we can make this project even better!😊

**Pull request merged**
